# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
fastlane_require 'dotenv'

lane :sign do

    create_keychain(
    name:               ENV['KEYCHAIN_NAME'],
    password:           ENV['KEYCHAIN_PASSWORD'],
    default_keychain:   false,
    unlock:             true,
    timeout:            3600,
    lock_when_sleeps:   true
  )
  
  match(
    git_url:            ENV['MATCH_GIT_URL'],
    git_branch:         ENV['MATCH_GIT_BRANCH'],
    keychain_name:      ENV['KEYCHAIN_NAME'],
    keychain_password:  ENV['KEYCHAIN_PASSWORD'],
    type:               ENV['MATCH_DISTRIBUTION_TYPE'],
    readonly:           true,
    platform:           ENV['PLATFORM'],
    app_identifier:     ENV['BUILD_BUNDLE_IDENTIFIER']
  )
end

lane :build do
  build_app(
    clean:          false,
    scheme:         ENV['BUILD_SCHEME'],
    output_name:    ENV['BUILD_OUTPUT_NAME'],
    configuration:  'Release',
  )
end
