name: iOS build work flow

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  job-setup:

    name: setup and test
    runs-on: [self-hosted, macmini-home]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Fastlane
        run: |
          cd GithubActionFastLaneTest
          gem list bundler
          gem install bundler
          echo gem installed new bundler
          bundle config set --local path 'vendor/cache'
          echo bundle path set
          
  
